"""L3 — la señal que la app tenía delante y no miraba.

`has_l3` valía **False en el 100 % de los casos** desde siempre, y con él
el pill «L3 · local scene trim» de la radiografía. Dos causas, y las dos
silenciosas:

- el regex buscaba `L3` en la salida de `dovi_tool info --summary`, que
  emite **exactamente cuatro** líneas de niveles al final —`L5 offsets`,
  `L2 trims`, `L8 trims`, `L9 MDP`— y ninguna de L3;
- la otra vía, `export --levels`, no pedía `level3`.

Medido sobre 21 MKVs CMv4.0 de la biblioteca: **los 21 tienen L3**, entre 1
y 224 combos en 90 s de muestra. Y sobre el RPU de un Blu-ray (P7 MEL, CM
v2.9) el export de `level3` sale **vacío**, así que L3 es aportación
exclusiva del bin y el merge que lo transfiere no pisa nada del disco.

Ejecutar desde la raíz del repo:
    python3 -m unittest app.tests.test_nivel_l3 -v
"""
import json
import sys
import tempfile
import unittest
from pathlib import Path

APP_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(APP_DIR))


def _write(d: Path, name: str, payload) -> Path:
    p = d / name
    p.write_text(json.dumps(payload), encoding="utf-8")
    return p


def _l3(n_combos: int, frames: int = 200) -> list:
    """Registros L3 con el formato REAL de `dovi_tool export --levels`."""
    return [{"frame": i, "min_pq_offset": 2048, "max_pq_offset": 2047,
             "avg_pq_offset": 1589 + (i % n_combos)} for i in range(frames)]


def _analizar(*, l3=None, l8_combos=0, scenes=0, frames=200):
    from phases.rpu_analyze import _parse_export_levels
    with tempfile.TemporaryDirectory() as td:
        d = Path(td)
        l1 = [{"frame": i, "min_pq": 0, "max_pq": 2081, "avg_pq": 819}
              for i in range(frames)]
        l8 = [{"frame": i, "length": 13, "target_display_index": 1,
               "trim_slope": 2048 + (i % l8_combos) * 31 if l8_combos else 2048,
               "trim_offset": 2048, "trim_power": 2048,
               "trim_chroma_weight": 2048, "trim_saturation_gain": 2048,
               "ms_weight": 2048}
              for i in range(frames)] if l8_combos else []
        paths = {
            "level1": _write(d, "l1.json", l1),
            "level2": _write(d, "l2.json", []),
            "level8": _write(d, "l8.json", l8),
        }
        if l3 is not None:
            paths["level3"] = _write(d, "l3.json", l3)
        if scenes:
            p = d / "scenes.json"
            paths["scenes"] = p
            paso = max(1, frames // scenes)
            p.write_text("".join(f"{i * paso}\n" for i in range(scenes)),
                         encoding="utf-8")
        return _parse_export_levels(paths)


class TestSeMideL3(unittest.TestCase):

    def test_el_export_de_level3_se_cuenta(self):
        a = _analizar(l3=_l3(37))
        self.assertEqual(a.l3_frames, 200)
        self.assertEqual(a.l3_unique_count, 37)

    def test_un_bin_con_l3_constante_da_un_combo(self):
        """The Amateur: un solo combo en sus 176.448 frames."""
        a = _analizar(l3=_l3(1))
        self.assertEqual(a.l3_unique_count, 1)

    def test_sin_bloques_l3_los_numeros_son_cero(self):
        """El caso del Blu-ray: su RPU CM v2.9 no trae L3 y el export sale
        vacío. No es un error, es que no lo tiene."""
        a = _analizar(l3=[])
        self.assertEqual((a.l3_frames, a.l3_unique_count), (0, 0))
        a = _analizar(l3=None)
        self.assertEqual((a.l3_frames, a.l3_unique_count), (0, 0))

    def test_level3_va_en_la_lista_base_del_export(self):
        """Si no se pide, no hay nada que contar — y el fallo es mudo."""
        from phases.rpu_analyze import _EXPORT_LEVELS
        self.assertIn("level3", _EXPORT_LEVELS)


class TestL3NoDecideNada(unittest.TestCase):
    """L3 se mide y se enseña, pero **no entra en el veredicto**.

    Esta clase fijaba lo contrario —un «rescate» por L3— durante unas
    horas del 2026-09-18, con el umbral heredado del de L8. El estudio
    posterior lo desmontó: sobre 40 bins del repo DoviTools el conteo de
    combos L3 acierta el **57 %** (azar) y su mediana es MAYOR en los
    generados (1.256) que en los retail (1.003). Aquel rescate habría
    rescatado exactamente los 22 bins que hay que descartar.

    El motivo lo dice Dolby: el mid tone offset que L3 codifica *«is
    generated by the Dolby Analysis»*. Es análisis, no autoría — como L1.

    Ojo con el atajo de «los generados no tienen L3»: es cierto de
    avdvplus/panni, que ponen identidad (2048,2048,2048), pero los bins
    `Generated` del repo son de `DoVi_Scripts` con `cm_analyze`, que sí lo
    calcula. De los 40 medidos, ninguno traía L3 identidad.
    """

    def _con(self, *, l3_combos, l8_delta, l8_count=2, scenes=0):
        from phases.rpu_analyze import RpuAnalysis
        from models import L8Combo
        a = RpuAnalysis()
        a.l8_unique_count = l8_count
        a.frames_with_cmv40 = 1000
        a.scene_cuts = scenes
        a.l3_unique_count = l3_combos
        a.l3_frames = 1000 if l3_combos else 0
        a.l8_combos = [L8Combo(
            target_display_index=1, trim_slope=2048 + l8_delta,
            trim_offset=2048, trim_power=2048, trim_chroma_weight=2048,
            trim_saturation_gain=2048, ms_weight=0,
            target_mid_contrast=None, clip_trim=None, occurrence_count=1000)]
        return a

    def test_un_l3_riquisimo_no_salva_un_l8_plano(self):
        """El caso de los 22 generados: L3 de cuatro cifras y L8 neutro."""
        from phases.rpu_analyze import classify_l8
        a = self._con(l3_combos=2583, l8_delta=0)
        self.assertEqual(classify_l8(a)[0], "default")

    def test_un_l3_ridiculo_no_hunde_un_l8_con_trabajo(self):
        """Posesión infernal: L3 en 88 frames de 159.030 y L8 con maxΔ 328."""
        from phases.rpu_analyze import classify_l8
        a = self._con(l3_combos=1, l8_delta=328)
        self.assertEqual(classify_l8(a)[0], "real")

    def test_el_veredicto_no_cambia_con_l3(self):
        """Mismo L8, cualquier L3: el resultado es idéntico."""
        from phases.rpu_analyze import classify_l8
        for delta, esperado in ((0, "default"), (328, "real")):
            vistos = {classify_l8(self._con(l3_combos=n, l8_delta=delta))[0]
                      for n in (0, 1, 50, 2583)}
            self.assertEqual(vistos, {esperado}, f"L3 alteró el veredicto con Δ={delta}")

    def test_el_tier_tampoco_lo_decide_l3(self):
        from phases.rpu_analyze import classify_l8_quality
        a = self._con(l3_combos=5000, l8_delta=300, l8_count=20, scenes=4000)
        b = self._con(l3_combos=0, l8_delta=300, l8_count=20, scenes=4000)
        self.assertEqual(classify_l8_quality(a)[0], classify_l8_quality(b)[0])


class TestElSummaryNoSirveParaEstosNiveles(unittest.TestCase):
    """Los patrones de L3/L4/L10/L11/L254 se retiraron del parseo del
    summary: no podían casar y hacían creer que algo se comprobaba."""

    def test_el_parseo_del_summary_ya_no_los_busca(self):
        src = (APP_DIR / "phases" / "phase_a.py").read_text(encoding="utf-8")
        for patron in ('r"L3\\b|Level 3', 'r"L4\\b|Level 4',
                       'r"L10\\b|Level 10', 'r"L11\\b|Level 11',
                       'r"L254\\b|Level 254'):
            with self.subTest(patron=patron):
                self.assertNotIn(patron, src)

    def test_el_summary_real_solo_trae_cuatro_niveles(self):
        """Copiado de `dovi_tool info --summary` sobre un bin del repo
        DoviTools. Si algún día emitiera más, este test lo dirá."""
        summary = (
            "Summary:\n  Frames: 155001\n  Profile: 7 (FEL)\n"
            "  DM version: 2 (CM v4.0)\n  Scene/shot count: 1929\n"
            "  RPU mastering display: 0.0001/1000 nits\n"
            "  RPU content light level (L1): MaxCLL: 996.13 nits, MaxFALL: 91.01 nits\n"
            "  L6 metadata\n"
            "  L5 offsets: top=276, bottom=276, left=0, right=0\n"
            "  L2 trims: 100 nits, 600 nits, 1000 nits\n"
            "  L8 trims: 100 nits, 600 nits\n"
            "  L9 MDP: DCI-P3 D65\n")
        for ausente in ("L3", "L4 ", "L10", "L11", "L254"):
            with self.subTest(nivel=ausente):
                self.assertNotIn(ausente, summary)

    def test_el_enriquecimiento_si_los_pide(self):
        src = (APP_DIR / "phases" / "mkv_analyze.py").read_text(encoding="utf-8")
        for nivel in ("level3", "level4", "level10", "level11"):
            with self.subTest(nivel=nivel):
                self.assertIn(f'"{nivel}"', src)


if __name__ == "__main__":
    unittest.main()
